[package]
name = "choreo"
version = "2024.2.3"
edition = "2021"
description = """\
  A graphical tool for planning time-optimized trajectories for autonomous \
  mobile robots in the FIRST Robotics Competition.\
  """
readme = "../README.md"
homepage = "https://github.com/SleipnirGroup/Choreo"
repository = "https://github.com/SleipnirGroup/Choreo.git"
license = "BSD-3-Clause"

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
tauri = { version = "1.6.6", features = ["devtools", "dialog", "dialog-ask", "dialog-confirm", "dialog-open", "dialog-save", "fs-all", "os-all", "path-all", "shell-open", "window-close", "window-set-title"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trajoptlib = { path = "../trajoptlib" }
open = "5.3.0"
tokio = { version = "1", features = ["full"] }
dashmap = "6.0.1"
thiserror = "1.0.63"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["ansi", "fmt", "std", "json"] }
clap = { version = "4.5.16", features = ["derive"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
